In [1]:
import numpy as np

In [3]:
some_array = np.arange(0, 12)
print(some_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
some_array = some_array.reshape(3,4)
print(some_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
some_array = some_array.reshape(2,6)
print(some_array)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [8]:
some_array = some_array.reshape(4, -1)
print(some_array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
some_array.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [12]:
array_1 = np.arange(15).reshape(5,3)
array_2 = np.arange(20).reshape(5,4)

print(array_1)
print("-----------------------\n")
print(array_2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
-----------------------

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [14]:
np.hstack((array_1, array_2))

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11],
       [ 9, 10, 11, 12, 13, 14, 15],
       [12, 13, 14, 16, 17, 18, 19]])

In [18]:
array_1d = np.arange(1,21)
print(array_1d)

list_1 = [ x/(x+1) for x in array_1d]
print(list_1)

f = np.vectorize(lambda x: x/(x+1))
f(array_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.9285714285714286, 0.9333333333333333, 0.9375, 0.9411764705882353, 0.9444444444444444, 0.9473684210526315, 0.95, 0.9523809523809523]


array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      , 0.95238095])

In [22]:
array_2d1 = np.arange(1,10).reshape(3,3)
array_2d2 = np.arange(10,19).reshape(3,3)
print(array_2d1)
print(array_2d2)
print("----------------------\n")
print(np.dot(array_2d1,array_2d2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
----------------------

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
