In [1]:
import numpy as np

In [2]:
array = np.array([2,3,4,5,6,7,8,900])
print(array)

[  2   3   4   5   6   7   8 900]


In [3]:
array += 100
print(array)

[ 102  103  104  105  106  107  108 1000]


In [5]:
list1 = [1,2,3]
#list1+=100
print(list1)

[1, 2, 3]


In [9]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
array_2d = array_2d**2
print(array_2d)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
