In [2]:
import numpy as np

In [5]:
arr1 = np.array([[1,2,3],
               [4,5,6]])
arr2 = np.array([[7,8,9],
               [10,11,12]])
arr3 = np.array([[7,8],[9,10],[11,12]])

In [6]:
print(arr1+arr2)

[[ 8 10 12]
 [14 16 18]]


In [7]:
print(np.dot(arr1,arr2))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [8]:
print(np.dot(arr1,arr3))

[[ 58  64]
 [139 154]]


In [17]:
np.shape(arr1) # No. of rows and columns

(2, 3)

In [14]:
np.ndim(arr3) # Dimension of matrix/array

2

In [15]:
np.size(arr2) # Total number of elements

6

In [20]:
print(arr3[1,1])
np.dtype(arr3[1,1])

10


dtype('int64')

In [21]:
arr3.T # Transpose of matrix

array([[ 7,  9, 11],
       [ 8, 10, 12]])

In [22]:
arr3

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [24]:
X = np.array([[4,2,5],[3,2,8],[5,2,9],[7,2,1]])
XT = X.T
U = np.dot(XT,X)
print(np.shape(U))

(3, 3)


In [37]:
I = np.identity(3,dtype=np.int64)

I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [49]:
sqarr = np.array([[1,2],
                 [3,4]],dtype=np.float64)
print(sqarr)
isqarr = np.linalg.inv(sqarr)
isqarr

[[1. 2.]
 [3. 4.]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [47]:
np.dot(sqarr,isqarr)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

Matrix Multiplication

In [50]:
A = np.array([[0,-1],
              [1,0]])
B = np.array([[1,1],
              [0,1]])
C = np.array([[0,1],
              [-1,0]])

CB = np.dot(C,B)
CBA1 = np.dot(CB,A)
print(CBA1)

[[ 1  0]
 [-1  1]]


In [52]:
BA = np.dot(B,A)
CBA2 = np.dot(C,BA)
print(CBA2)

[[ 1  0]
 [-1  1]]


In [59]:
A = np.array([[2, 3],
              [-1, 4]], dtype=np.int32)
round(np.linalg.det(A))

11.0

In [58]:
A = np.array([[4,1],
             [-1,2]], dtype=np.int32)
round(np.linalg.det(A))

9.0

In [60]:
A = np.array([[1,5,-1],
              [2,3,-2],
              [-3,4,0]])
b = np.array([[1],
              [2],
              [0]])
A_inv = np.linalg.inv(A)

x = np.dot(A_inv,b)

print(x)

[[ 0.]
 [ 0.]
 [-1.]]


In [61]:
A = np.array([[2,6,-1],
              [1,2,-2],
              [-5,0,2]])

b = ([[0],
      [1],
      [8]])

A_inv = np.linalg.inv(A)

x = np.dot(A_inv, b)

print(x)

[[-2. ]
 [ 0.5]
 [-1. ]]


In [3]:
A = np.array([[1,3],
              [2,6]])
np.linalg.matrix_rank(A)

1

In [8]:
A = np.array([[2,-1,-1],
              [2,-1,1],
              [4,-2,-3]])

b = np.array([1,0,-1])
print(np.linalg.matrix_rank(A))

A_inv = np.linalg.inv(A)


2


LinAlgError: Singular matrix