In [39]:
import numpy as np

In [40]:
v = np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [41]:
v[0]

0.0

In [42]:
v[1]

2.5

In [43]:
v[-1]

10.0

In [44]:
v[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:
vv = np.random.random((5,4))

In [ ]:
vv

In [ ]:
vv[0,0]

In [ ]:
vv[4,3]

In [ ]:
v[2:4]

In [ ]:
vv[2:5,1]

In [ ]:
vv[2:-1,2]

In [ ]:
vv[:,:]

In [ ]:
vv[:,::2]

In [51]:
v2 = v[2:4]
v2

array([5. , 7.5])

In [52]:
v2[0] = 1

In [53]:
v

array([ 0. ,  2.5,  1. ,  7.5, 10. ])

In [47]:
v3 = v.copy()
v3

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [54]:
v3[0] = 25

In [55]:
v

array([ 0. ,  2.5,  1. ,  7.5, 10. ])

In [56]:
v3

array([25. ,  2.5,  5. ,  7.5, 10. ])

In [57]:
v[[1,2,3]]

array([2.5, 1. , 7.5])

In [58]:
bool_index = v > 1
v[bool_index]

array([ 2.5,  7.5, 10. ])

In [59]:
v

array([ 0. ,  2.5,  1. ,  7.5, 10. ])