In [9]:
import numpy as np
import matplotlib.pyplot as pp

In [10]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [11]:
a.dtype

dtype('int64')

In [12]:
a = np.array([1,2,3,4,5],dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [13]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [14]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [15]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [16]:
np.zeros((3,3),'d')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.empty((4,4), 'd')

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 2.71736105e-322, 1.28822975e-231,
        1.28822975e-231],
       [4.44659081e-323, 1.16095484e-028, 1.10156806e-094,
        4.24819624e+180]])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.random.standard_normal((2,4))

array([[-0.56658039,  0.62842699, -1.45083397, -1.70230812],
       [ 1.04935584,  0.44081452,  1.13125462, -1.14778786]])

In [21]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

In [23]:
np.vstack([a,b])

array([[ 0.64743021,  0.34829937,  0.8082523 ],
       [ 1.25797741,  0.0696239 , -0.117661  ],
       [ 0.51961819, -0.53491575, -1.20735154],
       [-1.05029894, -0.18982877,  0.91466086]])

In [24]:
np.hstack([a,b])

array([[ 0.64743021,  0.34829937,  0.8082523 ,  0.51961819, -0.53491575,
        -1.20735154],
       [ 1.25797741,  0.0696239 , -0.117661  , -1.05029894, -0.18982877,
         0.91466086]])

In [25]:
a.transpose()

array([[ 0.64743021,  1.25797741],
       [ 0.34829937,  0.0696239 ],
       [ 0.8082523 , -0.117661  ]])

In [26]:
np.save('examples.npy',a)

In [27]:
a1 = np.load('examples.npy')

In [28]:
a1

array([[ 0.64743021,  0.34829937,  0.8082523 ],
       [ 1.25797741,  0.0696239 , -0.117661  ]])